name: Example Tag/Release CI
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Image Version'
        required: true
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "estebangfernandeza@gmail.com"
          git config --local user.name "Esteban Fernandez"
          git tag -a ${{ github.event.inputs.version }} -m "MiShop API Release ${{ github.event.inputs.version }}"
          git push origin ${{ github.event.inputs.version }}
  build:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build with Maven
        run: |
          echo "Building app v${{ github.event.inputs.version}}"
      - name: Build & Push Docker Image to DockerHub
        run: |
          echo "Pushing image ${{ github.event.inputs.version }} to Docker Registry"
