name: Tag/Release CI
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Image Version'
        required: true
jobs:

  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create Tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "estebangfernandeza@gmail.com"
          git config --local user.name "Esteban Fernandez"
          git tag -a ${{ github.event.inputs.version }} -m "Example Release ${{ github.event.inputs.version }}"
          git push origin ${{ github.event.inputs.version }}
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ github.event.inputs.version }}
        run: |
          echo "Creating Release $VERSION"
          CODE=$(
            curl  --location https://api.github.com/repos/estebanfern/github-release/releases --write-out '%{http_code}' --output /dev/null \
                  --header "Accept: application/vnd.github+json" \
                  --header "Authorization: Bearer $GITHUB_TOKEN" --data "{\"tag_name\": \"$VERSION\",\"target_commitish\": \"main\",\"name\": \"App Version $VERSION\",\"body\": \"Release of version $VERSION\",\"draft\": false,\"prerelease\": false,\"generate_release_notes\":false}"
          )
          if [ $CODE -eq 201 ];
          then
            echo "SUCCESS - $CODE"
            exit 0
          else
            echo "FAILURE - $CODE"
            exit 1
          fi

  build:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build App
        run: |
          echo "Building app v${{ github.event.inputs.version}}"
      - name: Build & Push Docker Image to DockerHub
        run: |
          echo "Pushing image ${{ github.event.inputs.version }} to Docker Registry"
